### ISSUE TITLE
Preferred/mandatory e-mail domain

### ISSUE THREAD

**Issue by laurivosandi** [codemowers/oidc-gateway#20]
User can change the primary e-mail in GH but that should not cause e-mail change on the IdP side. I suggest adding preferred/mandatory e-mail domain configuration option to the IdP config.

**Comment by veebkolm** [comment]
Should the email, that user can enter on the profile page, also be accounted by that configured domain (eg if user enters some email, but GH email having that domain, GH domain would still be primary)?

**Comment by veebkolm** [comment]
Implemented the solution as preferred domain always taking precedence
